services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: pAIk
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_USER: user
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pAIk
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - mysql

volumes:
  db-data: